package org.cath.ec.model;

// Generated Sep 25, 2012 5:38:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * Date generated by hbm2java
 */
public class Date implements java.io.Serializable {

    private Integer id;
    private String day;
    private String month;
    private String year;
    private String description;
    private SchoolYear schoolYear;

    public Date() {
    }

    public Date(SchoolYear schoolYear) {
        this.schoolYear = schoolYear;
    }

    public Date(String day, String month, String year, String description, SchoolYear schoolYear) {
        this.day = day;
        this.month = month;
        this.year = year;
        this.description = description;
        this.schoolYear = schoolYear;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDay() {
        return this.day;
    }

    public void setDay(String day) {
        this.day = day;
    }

    public String getMonth() {
        return this.month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public String getYear() {
        return this.year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public SchoolYear getSchoolYear() {
        return this.schoolYear;
    }

    public void setSchoolYear(SchoolYear schoolYear) {
        this.schoolYear = schoolYear;
    }

}
