package org.cath.ec.model;

// Generated Sep 25, 2012 5:38:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * Course generated by hbm2java
 */
public class Course extends AbstractModel {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String code;
    private String name;
    private Room room;
    private Session session;
    private Grade grade;
    private SchoolYear schoolYear;

    public Course() {
    }

    public Course(String code, String name) {
        this.code = code;
        this.name = name;
    }

    public Course(Room room, Session session, Grade grade, SchoolYear schoolYear) {
        this.room = room;
        this.session = session;
        this.grade = grade;
        this.schoolYear = schoolYear;
    }

    public Course(String code, String name, Room room, Session session, Grade grade, SchoolYear schoolYear) {
        this.code = code;
        this.name = name;
        this.room = room;
        this.session = session;
        this.grade = grade;
        this.schoolYear = schoolYear;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Room getRoom() {
        return this.room;
    }

    public void setRoom(Room room) {
        this.room = room;
    }

    public Session getSession() {
        return this.session;
    }

    public void setSession(Session session) {
        this.session = session;
    }

    public Grade getGrade() {
        return this.grade;
    }

    public void setGrade(Grade grade) {
        this.grade = grade;
    }

    public SchoolYear getSchoolYear() {
        return this.schoolYear;
    }

    public void setSchoolYear(SchoolYear schoolYear) {
        this.schoolYear = schoolYear;
    }
}
