package org.cath.ec.model;

// Generated Sep 19, 2012 12:31:23 AM by Hibernate Tools 3.4.0.CR1

/**
 * Date generated by hbm2java
 */
public class Date extends AbstractModel implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer id;
    private String day;
    private String month;
    private String year;
    private String description;
    private Integer yearId;

    public Date() {
    }

    public Date(String day, String month, String year, String description, Integer yearId) {
        this.day = day;
        this.month = month;
        this.year = year;
        this.description = description;
        this.yearId = yearId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDay() {
        return this.day;
    }

    public void setDay(String day) {
        this.day = day;
    }

    public String getMonth() {
        return this.month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public String getYear() {
        return this.year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getYearId() {
        return this.yearId;
    }

    public void setYearId(Integer yearId) {
        this.yearId = yearId;
    }

}
