package org.cath.ec.model;

import java.util.Calendar;

// Generated Sep 25, 2012 5:38:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * Date generated by hbm2java
 */
public class Date extends AbstractModel {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private int day;
    private int month;
    private int year;
    private String description;

    public Date() {
        Calendar cal = Calendar.getInstance();
        cal.setTime(new java.util.Date());
        day = cal.get(Calendar.DAY_OF_MONTH);
        month = cal.get(Calendar.MONTH) + 1;
        year = cal.get(Calendar.YEAR);
    }

    public Date(int day, int month, int year, String description) {
        this.day = day;
        this.month = month;
        this.year = year;
        this.description = description;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getDay() {
        return this.day;
    }

    public void setDay(int day) {
        this.day = day;
    }

    public int getMonth() {
        return this.month;
    }

    public void setMonth(int month) {
        this.month = month;
    }

    public int getYear() {
        return this.year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
