package org.cath.ec.model;

// Generated Sep 19, 2012 12:31:23 AM by Hibernate Tools 3.4.0.CR1

/**
 * Grade generated by hbm2java
 */
public class Grade implements java.io.Serializable {

    private int id;
    private String name;
    private Integer yearId;

    public Grade() {
    }

    public Grade(int id) {
        this.id = id;
    }

    public Grade(int id, String name, Integer yearId) {
        this.id = id;
        this.name = name;
        this.yearId = yearId;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getYearId() {
        return this.yearId;
    }

    public void setYearId(Integer yearId) {
        this.yearId = yearId;
    }

}
