package org.cath.ec.model;

// Generated Sep 19, 2012 12:31:23 AM by Hibernate Tools 3.4.0.CR1

/**
 * Room generated by hbm2java
 */
public class Room implements java.io.Serializable {

    private Integer id;
    private String name;
    private String description;
    private Integer yearId;

    public Room() {
    }

    public Room(String name, String description, Integer yearId) {
        this.name = name;
        this.description = description;
        this.yearId = yearId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getYearId() {
        return this.yearId;
    }

    public void setYearId(Integer yearId) {
        this.yearId = yearId;
    }

}
