package org.cath.ec.model;

// Generated Sep 25, 2012 5:38:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Year generated by hbm2java
 */
public class SchoolYear extends AbstractModel {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String name;
    private int year;
    private Date startDate;
    private Date endDate;
    private Set<Semester> semesters;
    private Set<Grade> grades;
    private Set<Session> sessions;
    private Set<Room> rooms;
    private Set<Course> courses;

    public SchoolYear() {
        Calendar cal = Calendar.getInstance();
        year = cal.get(Calendar.YEAR);
        Date d = new Date();
        startDate = d;
        endDate = d;

        semesters = new HashSet<Semester>(0);
        grades = new HashSet<Grade>(0);
        sessions = new HashSet<Session>(0);
        rooms = new HashSet<Room>(0);
        courses = new HashSet<Course>(0);
    }

    public SchoolYear(String name, Short year, Date startDate, Date endDate, Set<Semester> semesters, Set<Grade> grades,
            Set<Session> sessions, Set<Room> rooms, Set<Course> courses) {
        this.name = name;
        this.year = year;
        this.startDate = startDate;
        this.endDate = endDate;
        this.semesters = semesters;
        this.grades = grades;
        this.sessions = sessions;
        this.rooms = rooms;
        this.courses = courses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getYear() {
        return this.year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Set<Semester> getSemesters() {
        return this.semesters;
    }

    public void setSemesters(Set<Semester> semesters) {
        this.semesters = semesters;
    }

    public void addSemester(Semester semester) {
        this.semesters.add(semester);
    }

    public void removeSemester(Semester semester) {
        this.semesters.remove(semester);
    }

    public Set<Grade> getGrades() {
        return this.grades;
    }

    public void setGrades(Set<Grade> grades) {
        this.grades = grades;
    }

    public void addGrade(Grade grade) {
        this.grades.add(grade);
    }

    public void removeGrade(Grade grade) {
        this.grades.remove(grade);
    }

    public Set<Session> getSessions() {
        return this.sessions;
    }

    public void setSessions(Set<Session> sessions) {
        this.sessions = sessions;
    }

    public void addSession(Session session) {
        this.sessions.add(session);
    }

    public void removeSession(Session session) {
        this.sessions.remove(session);
    }

    public Set<Room> getRooms() {
        return this.rooms;
    }

    public void setRooms(Set<Room> rooms) {
        this.rooms = rooms;
    }

    public void addRoom(Room room) {
        this.rooms.add(room);
    }

    public void removeRoom(Room room) {
        this.rooms.remove(room);
    }

    public Set<Course> getCourses() {
        return this.courses;
    }

    public void setCourses(Set<Course> courses) {
        this.courses = courses;
    }

    public void addCourse(Course course) {
        this.courses.add(course);
    }

    public void removeCourse(Course course) {
        this.courses.remove(course);
    }

}
