package org.cath.ec.model;

// Generated Sep 25, 2012 5:38:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Year generated by hbm2java
 */
public class SchoolYear implements java.io.Serializable {

    private Integer id;
    private String name;
    private Short year;
    private Date startDate;
    private Date endDate;
    private Set<Semester> semesters = new HashSet<Semester>(0);
    private Set<Grade> grades = new HashSet<Grade>(0);
    private Set<Session> sessions = new HashSet<Session>(0);
    private Set<Room> rooms = new HashSet<Room>(0);
    private Set<Course> courses = new HashSet<Course>(0);

    public SchoolYear() {
    }

    public SchoolYear(String name, Short year, Date startDate, Date endDate, Set<Semester> semesters, Set<Grade> grades,
            Set<Session> sessions, Set<Room> rooms, Set<Course> courses) {
        this.name = name;
        this.year = year;
        this.startDate = startDate;
        this.endDate = endDate;
        this.semesters = semesters;
        this.grades = grades;
        this.sessions = sessions;
        this.rooms = rooms;
        this.courses = courses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Short getYear() {
        return this.year;
    }

    public void setYear(Short year) {
        this.year = year;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Set<Semester> getSemesters() {
        return this.semesters;
    }

    public void setSemesters(Set<Semester> semesters) {
        this.semesters = semesters;
    }

    public Set<Grade> getGrades() {
        return this.grades;
    }

    public void setGrades(Set<Grade> grades) {
        this.grades = grades;
    }

    public Set<Session> getSessions() {
        return this.sessions;
    }

    public void setSessions(Set<Session> sessions) {
        this.sessions = sessions;
    }

    public Set<Room> getRooms() {
        return this.rooms;
    }

    public void setRooms(Set<Room> rooms) {
        this.rooms = rooms;
    }

    public Set<Course> getCourses() {
        return this.courses;
    }

    public void setCourses(Set<Course> courses) {
        this.courses = courses;
    }

}
